#!/bin/sh
alias ls='ls -hH --group-directories-first --color=auto'
alias cp='cp -iv'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias more='less'
alias please='sudo $(fc -ln -1)'
